repos:
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv => make sure the lock file is up-to-date
        stages: [pre-commit]
        language: system
        entry: uv lock --locked
        always_run: true
        pass_filenames: false

      - id: documentation-formatting
        name: markdownlint => markdown formatting
        stages: [pre-commit]
        language: system
        entry: markdownlint --fix docs --disable MD013
        always_run: true
        pass_filenames: false

      - id: mkdocs-strict
        name: mkdocs => strict internal link check
        stages: [pre-push]
        language: system
        entry: uv run mkdocs build --strict
        always_run: true
        pass_filenames: false

      - id: pip-audit
        name: pip-audit => vulnerability checking
        stages: [pre-push]
        language: system
        entry: uv run pip-audit --ignore-vuln GHSA-c33w-24p9-8m24
        always_run: true
        pass_filenames: false
